name: Run screenshot tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1 #Setup Node
    - name: Run screenshot Tests
      run: |
        npm run test:screenshots:build
        npm run test:screenshots
        npm run test:screenshots:es2018

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
          name: screenshots
          path: |
            src/**/__image_snapshots__/**/*.png
